# .github/workflows/civitai_sync.yml
name: Civitai Creator Sync

on:
  # 1. 允许手动触发，并添加了新选项
  workflow_dispatch:
    inputs:
      creator_username:
        description: 'Creator Username to sync'
        required: true
        default: 'civitai'
      nsfw_level:
        description: 'NSFW Level'
        type: choice
        required: true
        default: 'X'
        options:
          - 'None'
          - 'Soft'
          - 'Mature'
          - 'X'
      sort_by:
        description: 'Sort Order'
        type: choice
        required: true
        default: 'Newest'
        options:
          - 'Newest'
          - 'Most Reactions'
          - 'Most Comments'
      threads:
        description: 'Download Threads (1-32)'
        type: number
        default: 16

  # 2. 定时触发：每天 0点 (UTC) 运行一次
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-and-report:
    runs-on: ubuntu-latest
    
    # 关键修复：授予 job 写入仓库的权限
    permissions:
      contents: write

    # 为定时任务设置默认值
    env:
      CREATOR_USERNAME: 'civitai' # 定时任务监控的默认作者
      NSFW_LEVEL: 'X'
      SORT_BY: 'Newest'
      THREADS: 16

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 4. Determine Parameters
        # 如果是手动触发，使用输入的参数覆盖默认值
        run: |
          if [ -n "${{ github.event.inputs.creator_username }}" ]; then
            echo "Running with manual inputs..."
            echo "CREATOR_USERNAME=${{ github.event.inputs.creator_username }}" >> $GITHUB_ENV
            echo "NSFW_LEVEL=${{ github.event.inputs.nsfw_level }}" >> $GITHUB_ENV
            echo "SORT_BY=${{ github.event.inputs.sort_by }}" >> $GITHUB_ENV
            echo "THREADS=${{ github.event.inputs.threads }}" >> $GITHUB_ENV
          else
            echo "Running with scheduled defaults..."
          fi

      - name: 5. Run Sync and Report Script
        run: |
          python sync_and_report.py \
            --username "${{ env.CREATOR_USERNAME }}" \
            --nsfw "${{ env.NSFW_LEVEL }}" \
            --sort "${{ env.SORT_BY }}" \
            --threads ${{ env.THREADS }} \
            --output-dir "./output"

      - name: 6. Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: Auto-sync for ${{ env.CREATOR_USERNAME }} (NSFW=${{ env.NSFW_LEVEL }}, Sort=${{ env.SORT_BY }})"
          # 更新文件匹配模式以包含新的清单文件名格式
          file_pattern: "output/*.json output/reports/*"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: 7. Upload New Images Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-images-${{ env.CREATOR_USERNAME }}-${{ github.run_id }}
          path: ./output/*.zip
          if-no-files-found: 'ignore'
